-- MySQL Script generated by MySQL Workbench
-- 12/04/16 16:04:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema online_kursevi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_kursevi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_kursevi` DEFAULT CHARACTER SET utf8 ;
USE `online_kursevi` ;

-- -----------------------------------------------------
-- Table `online_kursevi`.`Kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Kategorija` (
  `rbr` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rbr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Kurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Kurs` (
  `sifra` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `trajanje` INT NOT NULL,
  `max_ucesnika` INT NOT NULL,
  `Kategorija_rbr` INT NOT NULL,
  PRIMARY KEY (`sifra`),
  INDEX `fk_Kurs_Kategorija_idx` (`Kategorija_rbr` ASC),
  CONSTRAINT `fk_Kurs_Kategorija`
    FOREIGN KEY (`Kategorija_rbr`)
    REFERENCES `online_kursevi`.`Kategorija` (`rbr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Ciklus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Ciklus` (
  `datum_pocetka` DATE NOT NULL,
  `datum_kraja` DATE NOT NULL,
  `Kurs_sifra` INT NOT NULL,
  PRIMARY KEY (`datum_pocetka`, `Kurs_sifra`),
  INDEX `fk_Ciklus_Kurs1_idx` (`Kurs_sifra` ASC),
  CONSTRAINT `fk_Ciklus_Kurs1`
    FOREIGN KEY (`Kurs_sifra`)
    REFERENCES `online_kursevi`.`Kurs` (`sifra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Korisnik` (
  `kor_ime` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kor_ime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Ucesnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Ucesnik` (
  `poeni` INT NOT NULL,
  `Korisnik_kor_ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Korisnik_kor_ime`),
  CONSTRAINT `fk_Ucesnik_Korisnik1`
    FOREIGN KEY (`Korisnik_kor_ime`)
    REFERENCES `online_kursevi`.`Korisnik` (`kor_ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Predavac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Predavac` (
  `univerzitet` VARCHAR(45) NOT NULL,
  `Korisnik_kor_ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Korisnik_kor_ime`),
  CONSTRAINT `fk_Predavac_Korisnik1`
    FOREIGN KEY (`Korisnik_kor_ime`)
    REFERENCES `online_kursevi`.`Korisnik` (`kor_ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Prijavljuje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Prijavljuje` (
  `Ciklus_datum_pocetka` DATE NOT NULL,
  `Ciklus_Kurs_sifra` INT NOT NULL,
  `Ucesnik_Korisnik_kor_ime` VARCHAR(45) NOT NULL,
  `progres` TINYINT NOT NULL,
  PRIMARY KEY (`Ciklus_datum_pocetka`, `Ciklus_Kurs_sifra`, `Ucesnik_Korisnik_kor_ime`),
  INDEX `fk_Prijavljuje_Ucesnik1_idx` (`Ucesnik_Korisnik_kor_ime` ASC),
  CONSTRAINT `fk_Prijavljuje_Ciklus1`
    FOREIGN KEY (`Ciklus_datum_pocetka` , `Ciklus_Kurs_sifra`)
    REFERENCES `online_kursevi`.`Ciklus` (`datum_pocetka` , `Kurs_sifra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prijavljuje_Ucesnik1`
    FOREIGN KEY (`Ucesnik_Korisnik_kor_ime`)
    REFERENCES `online_kursevi`.`Ucesnik` (`Korisnik_kor_ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Predaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Predaje` (
  `Ciklus_datum_pocetka` DATE NOT NULL,
  `Ciklus_Kurs_sifra` INT NOT NULL,
  `Predavac_Korisnik_kor_ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ciklus_datum_pocetka`, `Ciklus_Kurs_sifra`, `Predavac_Korisnik_kor_ime`),
  INDEX `fk_Predaje_Predavac1_idx` (`Predavac_Korisnik_kor_ime` ASC),
  CONSTRAINT `fk_Predaje_Ciklus1`
    FOREIGN KEY (`Ciklus_datum_pocetka` , `Ciklus_Kurs_sifra`)
    REFERENCES `online_kursevi`.`Ciklus` (`datum_pocetka` , `Kurs_sifra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Predaje_Predavac1`
    FOREIGN KEY (`Predavac_Korisnik_kor_ime`)
    REFERENCES `online_kursevi`.`Predavac` (`Korisnik_kor_ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Lekcija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Lekcija` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(256) NOT NULL,
  `sadrzaj` TEXT NOT NULL,
  `Kurs_sifra` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lekcija_Kurs1_idx` (`Kurs_sifra` ASC),
  CONSTRAINT `fk_Lekcija_Kurs1`
    FOREIGN KEY (`Kurs_sifra`)
    REFERENCES `online_kursevi`.`Kurs` (`sifra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_kursevi`.`Sertifikat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_kursevi`.`Sertifikat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum_dodele` DATE NOT NULL,
  `Prijavljuje_Ciklus_datum_pocetka` DATE NOT NULL,
  `Prijavljuje_Ciklus_Kurs_sifra` INT NOT NULL,
  `Prijavljuje_Ucesnik_Korisnik_kor_ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sertifikat_Prijavljuje1_idx` (`Prijavljuje_Ciklus_datum_pocetka` ASC, `Prijavljuje_Ciklus_Kurs_sifra` ASC, `Prijavljuje_Ucesnik_Korisnik_kor_ime` ASC),
  CONSTRAINT `fk_Sertifikat_Prijavljuje1`
    FOREIGN KEY (`Prijavljuje_Ciklus_datum_pocetka` , `Prijavljuje_Ciklus_Kurs_sifra` , `Prijavljuje_Ucesnik_Korisnik_kor_ime`)
    REFERENCES `online_kursevi`.`Prijavljuje` (`Ciklus_datum_pocetka` , `Ciklus_Kurs_sifra` , `Ucesnik_Korisnik_kor_ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
